name: nyc-taxi
schedule: daily
start_date: "2022-01-01"

default_connections:
  bigquery: gcp-default

variables:
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow"]
#   other_string_var: (optional) Add your own variable and use it in both Python and SQL assets.
#     type: string
#     default: "my_value"
